import type { HanziCard } from '../types'
import { beiCard } from './bei'

type CachedCardInput = Omit<HanziCard, 'estimatedMinutes'>

function createCachedCard(card: CachedCardInput): HanziCard {
  return {
    estimatedMinutes: 5,
    ...card,
  }
}

export const mvpCachedCards: HanziCard[] = [
  beiCard,
  createCachedCard({
    slug: 'shui',
    character: '水',
    pinyin: 'shui',
    theme: '小河',
    heroLine: '今天跟着小水滴认识“水”。',
    storyScene: '一滴小水从云朵上跳下来，落进亮亮的小河里。',
    comic: {
      imageSrc: '/comics/shui.svg',
      alt: '小水滴从云朵落进小河',
      caption: '小水滴从云朵跳下来，顺着小河去旅行。',
      questions: ['画面里哪里有水？', '水可以帮我们做哪些事情？'],
    },
    storyText: '小水滴会流到杯子里，也会流到小河里。我们看见会流动、能喝、能洗手的东西，就想到了“水”。',
    parentPrompt: '让孩子看一看杯子或水龙头，慢慢说：“这是水，水会流。”',
    words: ['水杯', '水滴', '喝水'],
    sentences: ['我用水杯喝水。', '小水滴落到水里。'],
    activityPrompt: '找一找家里哪里有水，再轻轻说三遍“水”。',
  }),
  createCachedCard({
    slug: 'huo',
    character: '火',
    pinyin: 'huo',
    theme: '小火苗',
    heroLine: '今天看一看暖暖的小火苗，认识“火”。',
    storyScene: '一朵小火苗在营地灯旁跳来跳去，像在轻轻跳舞。',
    comic: {
      imageSrc: '/comics/huo.svg',
      alt: '小朋友远远看暖暖的小火苗',
      caption: '小火苗亮亮的、暖暖的，小朋友站在安全的地方看。',
      questions: ['小火苗是什么颜色？', '看见火的时候，我们要离近一点还是远一点？'],
    },
    storyText: '火会发光，也会变热。我们远远看、不要伸手碰，知道暖暖亮亮的小火苗就是“火”。',
    parentPrompt: '提醒孩子火只能远远看，再用手比一个小火苗往上跳的动作。',
    words: ['火苗', '火车', '火光'],
    sentences: ['小火苗发出火光。', '火车从远处开来了。'],
    activityPrompt: '用手指在空中画一朵小火苗，说一说“火”。',
  }),
  createCachedCard({
    slug: 'mu',
    character: '木',
    pinyin: 'mu',
    theme: '小树',
    heroLine: '今天和一棵小树一起认识“木”。',
    storyScene: '一棵小树站在草地上，树干直直的，树枝伸向两边。',
    comic: {
      imageSrc: '/comics/mu.svg',
      alt: '小朋友抱着树旁边的积木',
      caption: '树干直直地站着，旁边的积木也和木头有关。',
      questions: ['你能找到树干和树枝吗？', '家里有哪些东西可能是木头做的？'],
    },
    storyText: '小树有树干，也有树枝。桌子、积木、木门常常和树木有关，所以我们一起认识“木”。',
    parentPrompt: '指一指身边木头做的东西，告诉孩子：“这些都和木有关。”',
    words: ['木头', '树木', '积木'],
    sentences: ['树木长在山坡上。', '我用积木搭小屋。'],
    activityPrompt: '摸一摸积木或木桌，说说它硬硬的感觉。',
  }),
  createCachedCard({
    slug: 'ren',
    character: '人',
    pinyin: 'ren',
    theme: '朋友',
    heroLine: '今天从你和我开始认识“人”。',
    storyScene: '两个小朋友在森林小路上牵着手，一起往前走。',
    storyText: '会走路、会说话、会笑、会抱抱的，就是我们身边的人。你是人，我也是人，我们都是人。',
    parentPrompt: '和孩子互相指一指，说：“你是人，我也是人。”',
    words: ['大人', '小人', '家人'],
    sentences: ['家人一起吃饭。', '大人牵着小人走路。'],
    activityPrompt: '数一数房间里有几个人，再说出他们是谁。',
  }),
  createCachedCard({
    slug: 'kou',
    character: '口',
    pinyin: 'kou',
    theme: '小嘴巴',
    heroLine: '今天张开小嘴巴认识“口”。',
    storyScene: '小朋友张开嘴巴，轻轻吹出一个圆圆的泡泡。',
    storyText: '我们用口吃饭、说话、唱歌。看到张开的嘴巴，就可以想到这个方方的“口”。',
    parentPrompt: '请孩子轻轻张口说“啊”，再合上嘴巴笑一笑。',
    words: ['人口', '门口', '口水'],
    sentences: ['我站在门口等妈妈。', '小宝宝流了一点口水。'],
    activityPrompt: '用手在空中画一个方方的口，再读一读。',
  }),
  createCachedCard({
    slug: 'shan',
    character: '山',
    pinyin: 'shan',
    theme: '小山坡',
    heroLine: '今天爬一爬小山坡，认识“山”。',
    storyScene: '三座小山连在一起，中间高，两边低。',
    storyText: '山高高地站在地上，有的山长满树，有的山顶白白的。远远看到高高的山，我们就读“山”。',
    parentPrompt: '让孩子用手做三座小山的样子，边做边读“山”。',
    words: ['大山', '山坡', '山水'],
    sentences: ['大山后面有白云。', '我们在山坡上看风景。'],
    activityPrompt: '找一张有山的图片，指给家长看。',
  }),
  createCachedCard({
    slug: 'ri',
    character: '日',
    pinyin: 'ri',
    theme: '太阳',
    heroLine: '今天看见亮亮的太阳，认识“日”。',
    storyScene: '太阳从树梢后面升起来，把森林照得金黄金黄。',
    storyText: '白天太阳出来，世界变亮了。很久以前人们看到太阳，就常常想到“日”。',
    parentPrompt: '指向窗外的亮光，说：“白天有太阳，也可以说日光。”',
    words: ['日子', '日光', '生日'],
    sentences: ['今天是开心的日子。', '日光照在小花上。'],
    activityPrompt: '画一个圆圆的太阳，再在旁边写“日”。',
  }),
  createCachedCard({
    slug: 'yue',
    character: '月',
    pinyin: 'yue',
    theme: '月亮',
    heroLine: '今天抬头看看月亮，认识“月”。',
    storyScene: '弯弯的月亮挂在夜空，像一只小船慢慢飘。',
    storyText: '晚上天黑了，月亮出来陪我们。弯弯的月亮、圆圆的月亮，都和“月”有关。',
    parentPrompt: '晚上如果看得到月亮，就和孩子一起找一找；看不到也可以画一个。',
    words: ['月亮', '月牙', '明月'],
    sentences: ['月亮挂在天上。', '弯弯的月牙像小船。'],
    activityPrompt: '用手比一个弯弯的月牙，说“月亮出来啦”。',
  }),
  createCachedCard({
    slug: 'da',
    character: '大',
    pinyin: 'da',
    theme: '大大的拥抱',
    heroLine: '今天张开手臂认识“大”。',
    storyScene: '小朋友把两只手张得很开，想给家人一个大大的拥抱。',
    storyText: '东西很宽、很高、很多的时候，我们会说“大”。张开手臂做一个大动作，就像在说“大”。',
    parentPrompt: '和孩子比一比大苹果和小苹果，重点说“大”和“小”的感觉。',
    words: ['大人', '大山', '大门'],
    sentences: ['大人打开大门。', '大山看起来很高。'],
    activityPrompt: '找一个大东西，再找一个小东西，比一比。',
  }),
  createCachedCard({
    slug: 'xiao',
    character: '小',
    pinyin: 'xiao',
    theme: '小豆子',
    heroLine: '今天捡一颗小豆子，认识“小”。',
    storyScene: '一颗小豆子躲在叶子下面，圆圆的，轻轻的。',
    storyText: '小东西不大，拿在手里一点点。小豆子、小鞋子、小手，都可以带我们认识“小”。',
    parentPrompt: '用手指捏出一点点距离，告诉孩子：“这么一点点，就是小。”',
    words: ['小手', '小鸟', '小花'],
    sentences: ['小鸟站在小树上。', '我的小手拍拍拍。'],
    activityPrompt: '找一个小玩具，把它放在手心里看一看。',
  }),
  createCachedCard({
    slug: 'shang',
    character: '上',
    pinyin: 'shang',
    theme: '往上跳',
    heroLine: '今天让小叶子往上飞，认识“上”。',
    storyScene: '一片树叶被风吹起来，慢慢飞到树枝上面。',
    storyText: '在高处、在顶上，我们会说“上”。叶子飞上去，手举上去，都能帮我们记住“上”。',
    parentPrompt: '请孩子把手举到头顶，说：“手在上面。”',
    words: ['上面', '上山', '上车'],
    sentences: ['小鸟飞到树上。', '我们一起上山。'],
    activityPrompt: '把玩具放到桌子上，再说“在上面”。',
  }),
  createCachedCard({
    slug: 'xia',
    character: '下',
    pinyin: 'xia',
    theme: '往下落',
    heroLine: '今天看小雨点往下落，认识“下”。',
    storyScene: '小雨点从云朵下面落下来，落到小草旁边。',
    storyText: '从高处到低处，我们会说“下”。雨点落下，手放下，都是“下”的感觉。',
    parentPrompt: '让孩子先举高手，再慢慢放下，边做边说“下”。',
    words: ['下面', '下雨', '下来'],
    sentences: ['小雨从天上下来。', '猫咪躲在桌子下面。'],
    activityPrompt: '把玩具放到椅子下面，找一找在哪里。',
  }),
  createCachedCard({
    slug: 'zhong',
    character: '中',
    pinyin: 'zhong',
    theme: '中间',
    heroLine: '今天找一找中间的位置，认识“中”。',
    storyScene: '三棵树排成一排，小兔子站在中间那棵树旁。',
    storyText: '不在左边，也不在右边，站在正中间，我们就说“中”。小兔子站在中间，帮我们记住“中”。',
    parentPrompt: '摆三个玩具，让孩子指出中间的那个。',
    words: ['中间', '中国', '心中'],
    sentences: ['小兔站在中间。', '我心中有一个小愿望。'],
    activityPrompt: '排三块积木，指出中间的一块。',
  }),
  createCachedCard({
    slug: 'tian',
    character: '天',
    pinyin: 'tian',
    theme: '天空',
    heroLine: '今天抬头看看天空，认识“天”。',
    storyScene: '蓝蓝的天空很高很大，白云在上面慢慢走。',
    storyText: '我们抬头看到很高很高的地方，那就是天。晴天、雨天、蓝天，都藏着“天”。',
    parentPrompt: '带孩子看窗外，问：“今天的天是什么颜色？”',
    words: ['天空', '今天', '晴天'],
    sentences: ['今天是晴天。', '天空里有白云。'],
    activityPrompt: '看一眼窗外，说说今天是晴天还是雨天。',
  }),
  createCachedCard({
    slug: 'di',
    character: '地',
    pinyin: 'di',
    theme: '土地',
    heroLine: '今天踩一踩脚下的地，认识“地”。',
    storyScene: '小脚踩在草地上，旁边有泥土和小花。',
    storyText: '我们走路的时候，脚下面就是地。草地、土地、地面，都是可以站稳的地方。',
    parentPrompt: '请孩子跺一跺脚，感受脚下稳稳的地面。',
    words: ['土地', '地面', '草地'],
    sentences: ['小花长在土地里。', '我坐在草地上。'],
    activityPrompt: '轻轻跺两下脚，说“脚下是地”。',
  }),
  createCachedCard({
    slug: 'bai',
    character: '白',
    pinyin: 'bai',
    theme: '白云',
    heroLine: '今天摸一摸软软的白云，认识“白”。',
    storyScene: '一朵白云飘在蓝天上，像一团软软的棉花。',
    storyText: '雪是白的，云是白的，牛奶也是白的。看到干干净净、亮亮的颜色，我们说“白”。',
    parentPrompt: '找一个白色物品给孩子看，比如纸、杯子或小袜子。',
    words: ['白云', '白纸', '白天'],
    sentences: ['白云在天上飘。', '白纸上画了一朵花。'],
    activityPrompt: '在房间里找三个白色的东西。',
  }),
  createCachedCard({
    slug: 'yun',
    character: '云',
    pinyin: 'yun',
    theme: '云朵',
    heroLine: '今天跟着云朵慢慢飘，认识“云”。',
    storyScene: '几朵云在天空排成小队，像棉花糖一样飘过去。',
    storyText: '云在天上，有时白白的，有时灰灰的。风一吹，云就慢慢飘到远处。',
    parentPrompt: '和孩子看一看云的形状，问：“这朵云像什么？”',
    words: ['白云', '云朵', '乌云'],
    sentences: ['白云慢慢飘走了。', '乌云来了，可能要下雨。'],
    activityPrompt: '画一朵圆圆软软的云，再读“云”。',
  }),
  createCachedCard({
    slug: 'shou',
    character: '手',
    pinyin: 'shou',
    theme: '小手',
    heroLine: '今天伸出小手认识“手”。',
    storyScene: '小朋友伸出手，接住一片从树上落下来的叶子。',
    storyText: '我们用手拿东西、拍拍球、抱一抱家人。伸出小手看一看，就能认识“手”。',
    parentPrompt: '和孩子一起数手指，一边数一边说“这是我的手”。',
    words: ['小手', '手心', '拍手'],
    sentences: ['我的小手很能干。', '大家一起拍手笑。'],
    activityPrompt: '把手放在纸上描一圈，看看小手的样子。',
  }),
  createCachedCard({
    slug: 'xin',
    character: '心',
    pinyin: 'xin',
    theme: '爱心',
    heroLine: '今天抱一抱爱心，认识“心”。',
    storyScene: '一颗小爱心躲在口袋里，看到家人就轻轻发亮。',
    storyText: '我们开心、想念、喜欢的时候，心里会暖暖的。爱心的心，也就是今天认识的“心”。',
    parentPrompt: '把手放在胸口，和孩子说：“这里有一颗暖暖的心。”',
    words: ['开心', '爱心', '小心'],
    sentences: ['我今天很开心。', '过马路要小心。'],
    activityPrompt: '用两只手比一个爱心，送给身边的人。',
  }),
]
